---
title: "lab06hw"
author: "sylvia ho a18482382"
format: pdf
---

install.packages("bio3d")


```{r}
# Can you improve this analysis code?
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s1, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

```{r}
hc <- hclust( dist( rbind(s1.b, s2.b, s3.b) ) )
plot(hc)
```
q1. lists pdb objects
q2. select specific chains, residues, atom types, trim rest
q3. sse = NULL, sse = FALSE in plotb3(). secondary structure 
q4. single plot
q5. pairwise distances, dist()

```{r}

library(bio3d)


# read pdb, trim, plot
q6 <- function(pdb_id, chain = "A", elety = "CA") {
# read
pdb <- read.pdb(pdb_id)
# trim
pdb_trim <- trim.pdb(pdb, chain = chain, elety = elety)
# bfac
bfac <- pdb_trim$atom$b
# plot
plotb3(bfac,
sse = pdb_trim,
typ = "l",
ylab = "B-factor",
main = paste("B-factors for", pdb_id))
# return
return(bfac)
}

s1.b <-q6("4AKE") # kinase drug
s2.b <- q6("1AKE") # kinase no drug
s3.b <- q6("1E4Y") # kinase drug
```




